services:
  crypto_tracker:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - redis
      - postgres

  redis:
    image: 'redis:7.2.4-alpine'
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  
  postgres:
    image: 'postgres:16.2-bullseye'
    env_file:
      - .env
    ports: 
      - "5432:5432"
  
  celery:
    build: .
    command: celery -A apps.celery beat -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - crypto_tracker

volumes:
  data:
    driver: local
  redis_data:
