# Generated by Django 4.2.11 on 2024-04-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=128)),
                ('short_name', models.CharField(max_length=16)),
                ('price', models.CharField(max_length=32)),
                ('one_hour_change', models.CharField(max_length=16)),
                ('one_day_change', models.CharField(max_length=16)),
                ('one_week_change', models.CharField(max_length=16)),
                ('market_cap', models.CharField(max_length=16)),
                ('volume_in_dollars', models.CharField(max_length=16)),
                ('volume_in_crypto', models.CharField(max_length=16)),
                ('circulating_supply', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
