# Generated by Django 4.2.11 on 2024-04-28 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptodetail',
            name='circulating_supply',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='market_cap',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='volume_in_crypto',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='cryptodetail',
            name='volume_in_dollars',
            field=models.CharField(max_length=64),
        ),
    ]
