# Generated by Django 4.2.11 on 2024-04-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_tracker', '0002_alter_cryptodetail_circulating_supply_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
